# Generated by Django 2.0.3 on 2018-06-15 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20180517_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.Teams'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.Events'),
        ),
    ]
