# Generated by Django 2.0.4 on 2018-06-26 16:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_auto_20180615_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AddField(
            model_name='announcements',
            name='announce_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='announcements',
            name='announce_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='announcements',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcements',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-06-08T14:57:02.888000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(default='qaq'),
        ),
        migrations.AddField(
            model_name='events',
            name='excerpt',
            field=models.TextField(default='qaq'),
        ),
        migrations.AddField(
            model_name='events',
            name='regist_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='events',
            name='regist_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='events',
            name='rule',
            field=models.TextField(default='qaq'),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='vertify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profiles',
            name='is_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profiles',
            name='role_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profiles',
            name='token',
            field=models.CharField(default='QAQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=models.TextField(default='qaq'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='member_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='events',
            name='team_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profiles',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profiles',
            name='name',
            field=models.CharField(default='noname', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
