# Generated by Django 2.0.6 on 2018-06-27 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_auto_20180627_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_team', to='databases.Teams'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
