# Generated by Django 2.0.3 on 2018-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_auto_20180627_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
