# Generated by Django 2.0.3 on 2018-06-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_auto_20180627_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='member_max',
            field=models.IntegerField(default=10),
        ),
    ]
